### ISSUE TITLE
Make rule BR-DE-16 more precise

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/xrechnung-schematron#16]

**Comment by mircokuhlmann** [comment]
The descriptions of BR-DE-16 must be:

> In der Rechnung muss mindestens eines der Elemente „Seller VAT identifier“ (BT-31), „Seller tax registration identifier“ (BT-32) oder „SELLER TAX REPRESENTATIVE PARTY“ (BG-11) übermittelt werden.

**Comment by mircokuhlmann** [comment]
Umsetzung erledigt.
