### ISSUE TITLE
Make rules BR-DE-10 und BR-DE-11 more precise

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/xrechnung-schematron#18]

**Comment by mircokuhlmann** [comment]
Description of BR-DE-10 for CII, UBL-CN and UBL-Inv changed to
> Das Element „Deliver to city“ (BT-77) muss übermittelt werden, wenn die Gruppe „DELIVER TO ADDRESS“ (BG-15) übermittelt wird.

Description of BR-DE-11 for CII, UBL-CN and UBL-Inv changed to
> Das Element „Deliver to post code“ (BT-78) muss übermittelt werden, wenn die Gruppe „DELIVER TO ADDRESS“ (BG-15) übermittelt wird.
