### ISSUE TITLE
Follow up on possible new rules covering changes to BT-3

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/xrechnung-schematron#19]

**Comment by mircokuhlmann** [comment]
The business rule BR-DE-17 now also allows for code 389.

> Mit dem Element „Invoice type code“ (BT-3) sollen ausschließlich folgende
Codes aus der Codeliste UNTDID 1001a übermittelt werden:
• 326 (Partial invoice)
• 380 (Commercial invoice)
• 384 (Corrected invoice)
• 389 (Self-billed invoice)
• 381 (Credit note)

**Comment by mircokuhlmann** [comment]
Changes done for CII, UBL-Inv and UBL-CN.
