### ISSUE TITLE
Validation of International Bank Account Numbers (IBANs)

### ISSUE THREAD

**Issue by mircokuhlmann** [itplr-kosit/xrechnung-schematron#29]
The XRechnung validation artefacts should check IBANs regarding the syntax rules in ISO 13616-1 (Financial services — International bank account number (IBAN) — Part 1: Structure of the IBAN ).

**Comment by mircokuhlmann** [comment]
Rules BR-DE-19 and BR-DE-20 added for CII, UBL-Inv and UBL-CN.

Next step: Testing.

**Comment by rkottmann** [comment]
implemented and tested
