### ISSUE TITLE
Implementation of BR-DE-21

### ISSUE THREAD

**Issue by mircokuhlmann** [itplr-kosit/xrechnung-schematron#30]
BR-DE-21:

> Das Element „Specification identifier“ (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.

i. e., BT-24 must be equal to 
`urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2`

**Comment by mircokuhlmann** [comment]
Done (CII, UBL-INV, UBL-CN).

Next step: Testing.

**Comment by rkottmann** [comment]
tested
