### ISSUE TITLE
New EN16931 rule

### ISSUE THREAD

**Issue by phax** [itplr-kosit/xrechnung-schematron#4]
Hi guys,
just wanted to let you know that yesterday new EN 16931 rules were published - in case you're interested :)
https://github.com/CenPC434/validation/releases/tag/validation-1.1.0

// Philip

**Comment by rkottmann** [comment]
Hi Philip,

our schematron rules are independent of your EN16931 rules. However, our [Validator Configuration](https://github.com/itplr-kosit/validator-configuration-xrechnung) is very much dependent on your rules.

We are working on a new release including your new release and publish it soon.

Thanx for pinging us !
