### ISSUE TITLE
All existence rules for xml elements with simple content should also check for valid content

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/xrechnung-schematron#7]
There are some rules for XML elements with simple content which get checked for their existence, however, in most cases they are still allowed to be empty.

For example `<param name="BR-DE-3" value="cbc:CityName"/>` allows that the element is present but no city name is given (i.e. empty). But XRechnung requires a city name to be present.

Hence, I would suggest to change all these rules to something like:

`<param name="BR-DE-3" value="cbc:CityName[not( empty ( normalize-space( text() )))]"/>` or simpler XPath.

Some examples rules from [xrechnung-1_1-schematron-2017-12-19 release](https://github.com/itplr-kosit/xrechnung-schematron/blob/xrechnung-1_1-schematron-2017-12-19/validation/schematron/ubl-inv/UBL/XRechnung-UBL-model.sch) which might be affected:

```xml
    <param name="BR-DE-1 " value="cac:PaymentMeans"/>
    <param name="BR-DE-2" value="cac:Party/cac:Contact"/>
    <param name="BR-DE-3" value="cbc:CityName"/>
    <param name="BR-DE-4" value="cbc:PostalZone"/>
    <param name="BR-DE-5" value="cbc:Name"/>
    <param name="BR-DE-6" value="cbc:Telephone"/>
    <param name="BR-DE-7" value="cbc:ElectronicMail"/>
    <param name="BR-DE-8" value="cbc:CityName"/>
    <param name="BR-DE-9" value="cbc:PostalZone"/>
    <param name="BR-DE-10" value="cbc:CityName"/>
    <param name="BR-DE-11" value="cbc:PostalZone"/>
```

I am not sure if this requires a decission by our expert group.

**Comment by fbuettner-hb** [comment]
Simpler, and more explicit: 

```
string-length(cbc:CityName) gt 0
```

(string-length() is defined as 0 for an empty sequence, cf. https://www.w3.org/TR/xpath-functions/#func-string-length)

**Comment by rkottmann** [comment]
I just read in M. Kay's 'XSLT 2.0 and XPath 2.0' 4th Edition book p.881:

> It is not necessary to call string-length() to determine wheter a string is zero-length, because converting the string to an xs:boolean, either explicitly using boolean() function [...] returns true only if the string has a length of one or more characters. 

Hence `boolean(normalize-space(cbc:CityName))` is expressive and shorter.

**Comment by mircokuhlmann** [comment]
Jour Fixe: We use the "boolean()" alternative.

**Comment by mircokuhlmann** [comment]
Changes done for CII, UBL-Inv and UBL-CN.

Only Elements with simple types at syntax level have been resprected. The following rules were affected:

- BR-DE-3: "Seller city" (BT-37)
- BR-DE-4: "Seller post code" (BT-38)
- BR-DE-5: "Seller contact point" (BT-41)
- BR-DE-6: "Seller contact telephone number" (BT-42)
- BR-DE-7: "Seller contact email address" (BT-43)
- BR-DE-8: "Buyer city" (BT-52)
- BR-DE-9: "Buyer post code" (BT-53)
- BR-DE-10: "Deliver to city" (BT-77)
- BR-DE-11: "Deliver to post code" (BT-78)
- BR-DE-14: "VAT category rate" (BT-119)
- BR-DE-15: "Buyer reference" (BT-10)
- BR-DE-16: "Seller VAT identifier" (BT-31), "Seller tax registration identifier" (BT-32)

**Comment by mircokuhlmann** [comment]
Next step: Testing.

Expected result: Elements including only whitspaces should now be forbidden.

**Comment by mircokuhlmann** [comment]
Test result: Rules are not robust with respect to multiple occurrences of elements.

**Comment by mircokuhlmann** [comment]
The rules have been changed from
`boolean(normalize-space(<element>))` to
`<element>[boolean(normalize-space(.))]`.

**Comment by mircokuhlmann** [comment]
Next step: Testing.
